- name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: 'ichi-translator-rebuilt-20240523'
          package: '.' # 現在のディレクトリ（host.jsonがある場所）をそのまま送る
          # 以下の 1 行を追加してください
          remote-build: true