name: Deploy Python Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Python version'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './'
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          popd

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        id: deploy-to-function
        uses: Azure/functions-action@v1
        with:
          app-name: 'ichi-translator-rebuilt-20240523'
          package: './'
